import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const sourceDir = path.join(repoRoot, "prompt-sources");
const outputFile = path.join(repoRoot, "convex", "data", "generated", "promptLibrary.ts");

async function collectMarkdownFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectMarkdownFiles(fullPath)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".md") && entry.name.toLowerCase() !== "readme.md") {
      files.push(fullPath);
    }
  }

  return files.sort();
}

function toKey(relativePath) {
  return relativePath
    .replace(/\\/g, "/")
    .replace(/\.md$/i, "")
    .split("/")
    .map((segment, index) => {
      const cleaned = segment.replace(/[^a-zA-Z0-9]+/g, " ").trim();
      if (!cleaned) return "";
      const words = cleaned.split(/\s+/);
      return words
        .map((word, wordIndex) => {
          const lower = word.toLowerCase();
          if (index === 0 && wordIndex === 0) return lower;
          return lower.charAt(0).toUpperCase() + lower.slice(1);
        })
        .join("");
    })
    .join("");
}

async function main() {
  const markdownFiles = await collectMarkdownFiles(sourceDir);
  const entries = await Promise.all(
    markdownFiles.map(async (fullPath) => {
      const relativePath = path.relative(sourceDir, fullPath);
      const key = toKey(relativePath);
      const content = await readFile(fullPath, "utf8");
      return { key, relativePath: relativePath.replace(/\\/g, "/"), content };
    })
  );

  const lines = [
    "// Auto-generated by scripts/sync-prompts.mjs. Do not edit by hand.",
    "",
    "export const PROMPT_LIBRARY = {",
    ...entries.map(
      (entry) => `  ${entry.key}: ${JSON.stringify(entry.content.trim())},`
    ),
    "} as const;",
    "",
    "export type PromptLibraryKey = keyof typeof PROMPT_LIBRARY;",
    "",
    "export const PROMPT_SOURCE_FILES = {",
    ...entries.map(
      (entry) => `  ${entry.key}: ${JSON.stringify(entry.relativePath)},`
    ),
    "} as const;",
    "",
  ];

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, lines.join("\n"), "utf8");
  console.log(`Synced ${entries.length} prompt source files to ${path.relative(repoRoot, outputFile)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

